[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pendropy"
version = "0.1.0"
description = "Python framework for pendant-drop analysis of elastic interfaces."
requires-python = ">=3.9"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "h5py",
]

[tool.setuptools.packages.find]
include = ["pendropy*"]
